1 #! /usr/bin/env python3
2 #  -*- coding: utf-8 -*-
3 #
4 # GUI module generated by PAGE version 8.0
5 #  in conjunction with Tcl version 8.6
6 #    Jun 19, 2025 04:43:49 PM CEST  platform: Windows NT
7 
8 import sys
9 import tkinter as tk
10 import tkinter.ttk as ttk
11 from tkinter.constants import *
12 import os.path
13 
14 _location = os.path.dirname(__file__)
15 
16 import fertiger_dialog_support
17 
18 _bgcolor = '#d9d9d9'
19 _fgcolor = '#000000'
20 _tabfg1 = 'black' 
21 _tabfg2 = 'white' 
22 _bgmode = 'light' 
23 _tabbg1 = '#d9d9d9' 
24 _tabbg2 = 'gray40' 
25 
26 _style_code_ran = 0
27 def _style_code():
28     global _style_code_ran
29     if _style_code_ran: return		
30     try: fertiger_dialog_support.root.tk.call('source',
31                 os.path.join(_location, 'themes', 'default.tcl'))
32     except: pass
33     style = ttk.Style()
34     style.theme_use('default')
35     style.configure('.', font = "TkDefaultFont")
36     if sys.platform == "win32":
37        style.theme_use('winnative')	
38     _style_code_ran = 1
39 
40 class Toplevel1:
41     def __init__(self, top=None):
42         '''This class configures and populates the toplevel window.
43            top is the toplevel containing window.'''
44 
45         top.geometry("589x350+923+44")
46         top.minsize(120, 1)
47         top.maxsize(1924, 1041)
48         top.resizable(1,  1)
49         top.title("Toplevel 0")
50         top.configure(background="#d9d9d9")
51         top.configure(highlightbackground="#d9d9d9")
52         top.configure(highlightcolor="#000000")
53 
54         self.top = top
55         self.combobox = tk.StringVar()
56         self.che64 = tk.IntVar()
57         self.che68 = tk.IntVar()
58         self.che79 = tk.IntVar()
59         self.che81 = tk.IntVar()
60 
61         self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
62         top.configure(menu = self.menubar)
63 
64         self.sub_menu = tk.Menu(self.menubar, activebackground='#d9d9d9'
65                 ,activeborderwidth=1, activeforeground='black'
66                 ,background='#d9d9d9', borderwidth=1, disabledforeground='#a3a3a3'
67                 ,font="-family {Segoe UI} -size 9", foreground='#000000'
68                 ,tearoff=0)
69         self.menubar.add_cascade(compound='left'
70                 ,font="-family {Segoe UI} -size 9", label='File'
71                 ,menu=self.sub_menu, )
72         self.sub_menu.add_command(compound='left'
73                 ,font="-family {Segoe UI} -size 9", label='Load...')
74         self.sub_menu.add_command(compound='left'
75                 ,font="-family {Segoe UI} -size 9", label='Save...')
76         self.sub_menu.add_command(compound='left'
77                 ,font="-family {Segoe UI} -size 9", label='Close')
78         self.sub_menu1 = tk.Menu(self.menubar, activebackground='#d9d9d9'
79                 ,activeborderwidth=1, activeforeground='black'
80                 ,background='#d9d9d9', borderwidth=1, disabledforeground='#a3a3a3'
81                 ,font="-family {Segoe UI} -size 9", foreground='#000000'
82                 ,tearoff=0)
83         self.menubar.add_cascade(compound='left'
84                 ,font="-family {Segoe UI} -size 9", label='Updater'
85                 ,menu=self.sub_menu1, )
86         self.sub_menu1.add_command(compound='left'
87                 ,font="-family {Segoe UI} -size 9", label='Schedule on')
88         self.sub_menu1.add_command(compound='left'
89                 ,font="-family {Segoe UI} -size 9", label='Schedule off')
90         self.sub_menu1.add_command(compound='left'
91                 ,font="-family {Segoe UI} -size 9", label='Restart')
92         self.sub_menu12 = tk.Menu(self.menubar, activebackground='#d9d9d9'
93                 ,activeborderwidth=1, activeforeground='black'
94                 ,background='#d9d9d9', borderwidth=1, disabledforeground='#a3a3a3'
95                 ,font="-family {Segoe UI} -size 9", foreground='#000000'
96                 ,tearoff=0)
97         self.menubar.add_cascade(compound='left'
98                 ,font="-family {Segoe UI} -size 9", label='Backup'
99                 ,menu=self.sub_menu12, )
100         self.sub_menu12.add_command(compound='left'
101                 ,font="-family {Segoe UI} -size 9", label='Schedule on')
102         self.sub_menu12.add_command(compound='left'
103                 ,font="-family {Segoe UI} -size 9", label='Schedule off')
104         self.sub_menu12.add_command(compound='left'
105                 ,font="-family {Segoe UI} -size 9", label='Backup now')
106 
107         _style_code()
108         self.tabs = ttk.Notebook(self.top)
109         self.tabs.place(relx=0.0, rely=0.0, relheight=0.591, relwidth=1.003)
110         self.tabs_t1 = tk.Frame(self.tabs)
111         self.tabs.add(self.tabs_t1, padding=3)
112         self.tabs.tab(0, text='''Server''',compound="left",underline='''-1''',)
113         self.tabs_t1.configure(background="#d9d9d9")
114         self.tabs_t1.configure(highlightbackground="#d9d9d9")
115         self.tabs_t1.configure(highlightcolor="#000000")
116         self.tabs_t2 = tk.Frame(self.tabs)
117         self.tabs.add(self.tabs_t2, padding=3)
118         self.tabs.tab(1, text='''Updater''', compound="left", underline='''-1'''
119                 ,)
120         self.tabs_t2.configure(background="#d9d9d9")
121         self.tabs_t2.configure(highlightbackground="#d9d9d9")
122         self.tabs_t2.configure(highlightcolor="#000000")
123         self.tabs_t3 = tk.Frame(self.tabs)
124         self.tabs.add(self.tabs_t3, padding=3)
125         self.tabs.tab(2, text='''Backup''',compound="left",underline='''-1''',)
126         self.tabs_t3.configure(background="#d9d9d9")
127         self.tabs_t3.configure(highlightbackground="#d9d9d9")
128         self.tabs_t3.configure(highlightcolor="#000000")
129         self.tabs_t4 = tk.Frame(self.tabs)
130         self.tabs.add(self.tabs_t4, padding=3)
131         self.tabs.tab(3, text='''Optionen''', compound="left", underline='''-1'''
132                 ,)
133         self.tabs_t4.configure(background="#d9d9d9")
134         self.tabs_t4.configure(highlightbackground="#d9d9d9")
135         self.tabs_t4.configure(highlightcolor="#000000")
136 
137         self.frame_ftpDirectory = tk.LabelFrame(self.tabs_t1)
138         self.frame_ftpDirectory.place(relx=0.616, rely=0.044, relheight=0.328
139                 , relwidth=0.368)
140         self.frame_ftpDirectory.configure(relief='groove')
141         self.frame_ftpDirectory.configure(font="-family {Segoe UI} -size 9")
142         self.frame_ftpDirectory.configure(foreground="#000000")
143         self.frame_ftpDirectory.configure(text='''Savegame Verzeichnis''')
144         self.frame_ftpDirectory.configure(background="#d9d9d9")
145         self.frame_ftpDirectory.configure(highlightbackground="#d9d9d9")
146         self.frame_ftpDirectory.configure(highlightcolor="#000000")
147 
148         self.label_ftpDirectory = tk.Label(self.frame_ftpDirectory)
149         self.label_ftpDirectory.place(relx=0.092, rely=0.267, height=15
150                 , width=191, bordermode='ignore')
151         self.label_ftpDirectory.configure(activebackground="#d9d9d9")
152         self.label_ftpDirectory.configure(activeforeground="black")
153         self.label_ftpDirectory.configure(anchor='w')
154         self.label_ftpDirectory.configure(background="#d9d9d9")
155         self.label_ftpDirectory.configure(compound='left')
156         self.label_ftpDirectory.configure(disabledforeground="#a3a3a3")
157         self.label_ftpDirectory.configure(font="-family {Segoe UI} -size 9")
158         self.label_ftpDirectory.configure(foreground="#000000")
159         self.label_ftpDirectory.configure(highlightbackground="#d9d9d9")
160         self.label_ftpDirectory.configure(highlightcolor="#000000")
161         self.label_ftpDirectory.configure(text='''Standard: /savegame''')
162 
163         self.entry_ftpDirectory = tk.Entry(self.frame_ftpDirectory)
164         self.entry_ftpDirectory.place(relx=0.092, rely=0.467, height=20
165                 , relwidth=0.848, bordermode='ignore')
166         self.entry_ftpDirectory.configure(background="white")
167         self.entry_ftpDirectory.configure(disabledforeground="#a3a3a3")
168         self.entry_ftpDirectory.configure(font="-family {Courier New} -size 10")
169         self.entry_ftpDirectory.configure(foreground="#000000")
170         self.entry_ftpDirectory.configure(highlightbackground="#d9d9d9")
171         self.entry_ftpDirectory.configure(highlightcolor="#000000")
172         self.entry_ftpDirectory.configure(insertbackground="#000000")
173         self.entry_ftpDirectory.configure(selectbackground="#d9d9d9")
174         self.entry_ftpDirectory.configure(selectforeground="black")
175 
176         self.frame_ftpConnection = tk.LabelFrame(self.tabs_t1)
177         self.frame_ftpConnection.place(relx=0.616, rely=0.393, relheight=0.541
178                 , relwidth=0.368)
179         self.frame_ftpConnection.configure(relief='groove')
180         self.frame_ftpConnection.configure(font="-family {Segoe UI} -size 9")
181         self.frame_ftpConnection.configure(foreground="#000000")
182         self.frame_ftpConnection.configure(text='''Verbindung''')
183         self.frame_ftpConnection.configure(background="#d9d9d9")
184         self.frame_ftpConnection.configure(highlightbackground="#d9d9d9")
185         self.frame_ftpConnection.configure(highlightcolor="#000000")
186 
187         self.canvas_ftpConnection = tk.Canvas(self.frame_ftpConnection)
188         self.canvas_ftpConnection.place(relx=0.046, rely=0.162, relheight=0.505
189                 , relwidth=0.922, bordermode='ignore')
190         self.canvas_ftpConnection.configure(background="#d9d9d9")
191         self.canvas_ftpConnection.configure(borderwidth="2")
192         self.canvas_ftpConnection.configure(highlightbackground="#d9d9d9")
193         self.canvas_ftpConnection.configure(highlightcolor="#000000")
194         self.canvas_ftpConnection.configure(insertbackground="#000000")
195         self.canvas_ftpConnection.configure(relief="ridge")
196         self.canvas_ftpConnection.configure(selectbackground="#d9d9d9")
197         self.canvas_ftpConnection.configure(selectforeground="black")
198 
199         self.btn_ftpConnectionTest = tk.Button(self.frame_ftpConnection)
200         self.btn_ftpConnectionTest.place(relx=0.226, rely=0.717, height=26
201                 , width=47, bordermode='ignore')
202         self.btn_ftpConnectionTest.configure(activebackground="#d9d9d9")
203         self.btn_ftpConnectionTest.configure(activeforeground="black")
204         self.btn_ftpConnectionTest.configure(background="#d9d9d9")
205         self.btn_ftpConnectionTest.configure(disabledforeground="#a3a3a3")
206         self.btn_ftpConnectionTest.configure(font="-family {Segoe UI} -size 9")
207         self.btn_ftpConnectionTest.configure(foreground="#000000")
208         self.btn_ftpConnectionTest.configure(highlightbackground="#d9d9d9")
209         self.btn_ftpConnectionTest.configure(highlightcolor="#000000")
210         self.btn_ftpConnectionTest.configure(text='''Testen''')
211 
212         self.btn_ftpConnectionSave = tk.Button(self.frame_ftpConnection)
213         self.btn_ftpConnectionSave.place(relx=0.502, rely=0.717, height=26
214                 , width=67, bordermode='ignore')
215         self.btn_ftpConnectionSave.configure(activebackground="#d9d9d9")
216         self.btn_ftpConnectionSave.configure(activeforeground="black")
217         self.btn_ftpConnectionSave.configure(background="#d9d9d9")
218         self.btn_ftpConnectionSave.configure(disabledforeground="#a3a3a3")
219         self.btn_ftpConnectionSave.configure(font="-family {Segoe UI} -size 9")
220         self.btn_ftpConnectionSave.configure(foreground="#000000")
221         self.btn_ftpConnectionSave.configure(highlightbackground="#d9d9d9")
222         self.btn_ftpConnectionSave.configure(highlightcolor="#000000")
223         self.btn_ftpConnectionSave.configure(text='''Speichern''')
224 
225         self.frame_FTP = tk.LabelFrame(self.tabs_t1)
226         self.frame_FTP.place(relx=0.017, rely=0.055, relheight=0.891
227                 , relwidth=0.582)
228         self.frame_FTP.configure(relief='groove')
229         self.frame_FTP.configure(font="-family {Segoe UI} -size 9")
230         self.frame_FTP.configure(foreground="#000000")
231         self.frame_FTP.configure(text='''FTP-Zugangsdaten''')
232         self.frame_FTP.configure(background="#d9d9d9")
233         self.frame_FTP.configure(highlightbackground="#d9d9d9")
234         self.frame_FTP.configure(highlightcolor="#000000")
235 
236         self.label_ftpHost = tk.Label(self.frame_FTP)
237         self.label_ftpHost.place(relx=0.029, rely=0.196, height=16, width=82
238                 , bordermode='ignore')
239         self.label_ftpHost.configure(activebackground="#d9d9d9")
240         self.label_ftpHost.configure(activeforeground="black")
241         self.label_ftpHost.configure(anchor='w')
242         self.label_ftpHost.configure(background="#d9d9d9")
243         self.label_ftpHost.configure(compound='left')
244         self.label_ftpHost.configure(disabledforeground="#a3a3a3")
245         self.label_ftpHost.configure(font="-family {Segoe UI} -size 9")
246         self.label_ftpHost.configure(foreground="#000000")
247         self.label_ftpHost.configure(highlightbackground="#d9d9d9")
248         self.label_ftpHost.configure(highlightcolor="#000000")
249         self.label_ftpHost.configure(text='''FTP Host:''')
250 
251         self.entry_ftpHost = tk.Entry(self.frame_FTP)
252         self.entry_ftpHost.place(relx=0.344, rely=0.196, height=20
253                 , relwidth=0.624, bordermode='ignore')
254         self.entry_ftpHost.configure(background="white")
255         self.entry_ftpHost.configure(disabledforeground="#a3a3a3")
256         self.entry_ftpHost.configure(font="-family {Courier New} -size 10")
257         self.entry_ftpHost.configure(foreground="#000000")
258         self.entry_ftpHost.configure(highlightbackground="#d9d9d9")
259         self.entry_ftpHost.configure(highlightcolor="#000000")
260         self.entry_ftpHost.configure(insertbackground="#000000")
261         self.entry_ftpHost.configure(selectbackground="#d9d9d9")
262         self.entry_ftpHost.configure(selectforeground="black")
263         self.entry_ftpHost_tooltip = \
264         ToolTip(self.entry_ftpHost, '''FTP Host ohne Port eintragen''')
265 
266         self.label_ftpPort = tk.Label(self.frame_FTP)
267         self.label_ftpPort.place(relx=0.029, rely=0.393, height=16, width=82
268                 , bordermode='ignore')
269         self.label_ftpPort.configure(activebackground="#d9d9d9")
270         self.label_ftpPort.configure(activeforeground="black")
271         self.label_ftpPort.configure(anchor='w')
272         self.label_ftpPort.configure(background="#d9d9d9")
273         self.label_ftpPort.configure(compound='left')
274         self.label_ftpPort.configure(disabledforeground="#a3a3a3")
275         self.label_ftpPort.configure(font="-family {Segoe UI} -size 9")
276         self.label_ftpPort.configure(foreground="#000000")
277         self.label_ftpPort.configure(highlightbackground="#d9d9d9")
278         self.label_ftpPort.configure(highlightcolor="#000000")
279         self.label_ftpPort.configure(text='''FTP Port:''')
280 
281         self.entry_ftpPort = tk.Entry(self.frame_FTP)
282         self.entry_ftpPort.place(relx=0.344, rely=0.393, height=20
283                 , relwidth=0.303, bordermode='ignore')
284         self.entry_ftpPort.configure(background="white")
285         self.entry_ftpPort.configure(disabledforeground="#a3a3a3")
286         self.entry_ftpPort.configure(font="-family {Courier New} -size 10")
287         self.entry_ftpPort.configure(foreground="#000000")
288         self.entry_ftpPort.configure(highlightbackground="#d9d9d9")
289         self.entry_ftpPort.configure(highlightcolor="#000000")
290         self.entry_ftpPort.configure(insertbackground="#000000")
291         self.entry_ftpPort.configure(selectbackground="#d9d9d9")
292         self.entry_ftpPort.configure(selectforeground="black")
293         self.entry_ftpPort_tooltip = \
294         ToolTip(self.entry_ftpPort, '''FTP Host ohne Port eintragen''')
295 
296         self.label_ftpUser = tk.Label(self.frame_FTP)
297         self.label_ftpUser.place(relx=0.029, rely=0.583, height=17, width=82
298                 , bordermode='ignore')
299         self.label_ftpUser.configure(activebackground="#d9d9d9")
300         self.label_ftpUser.configure(activeforeground="black")
301         self.label_ftpUser.configure(anchor='w')
302         self.label_ftpUser.configure(background="#d9d9d9")
303         self.label_ftpUser.configure(compound='left')
304         self.label_ftpUser.configure(disabledforeground="#a3a3a3")
305         self.label_ftpUser.configure(font="-family {Segoe UI} -size 9")
306         self.label_ftpUser.configure(foreground="#000000")
307         self.label_ftpUser.configure(highlightbackground="#d9d9d9")
308         self.label_ftpUser.configure(highlightcolor="#000000")
309         self.label_ftpUser.configure(text='''FTP Benutzer:''')
310 
311         self.entry_ftpUser = tk.Entry(self.frame_FTP)
312         self.entry_ftpUser.place(relx=0.344, rely=0.583, height=20
313                 , relwidth=0.624, bordermode='ignore')
314         self.entry_ftpUser.configure(background="white")
315         self.entry_ftpUser.configure(disabledforeground="#a3a3a3")
316         self.entry_ftpUser.configure(font="-family {Courier New} -size 10")
317         self.entry_ftpUser.configure(foreground="#000000")
318         self.entry_ftpUser.configure(highlightbackground="#d9d9d9")
319         self.entry_ftpUser.configure(highlightcolor="#000000")
320         self.entry_ftpUser.configure(insertbackground="#000000")
321         self.entry_ftpUser.configure(selectbackground="#d9d9d9")
322         self.entry_ftpUser.configure(selectforeground="black")
323         self.entry_ftpUser_tooltip = \
324         ToolTip(self.entry_ftpUser, '''FTP Host ohne Port eintragen''')
325 
326         self.label_ftpPassword = tk.Label(self.frame_FTP)
327         self.label_ftpPassword.place(relx=0.029, rely=0.81, height=17, width=82
328                 , bordermode='ignore')
329         self.label_ftpPassword.configure(activebackground="#d9d9d9")
330         self.label_ftpPassword.configure(activeforeground="black")
331         self.label_ftpPassword.configure(anchor='w')
332         self.label_ftpPassword.configure(background="#d9d9d9")
333         self.label_ftpPassword.configure(compound='left')
334         self.label_ftpPassword.configure(disabledforeground="#a3a3a3")
335         self.label_ftpPassword.configure(font="-family {Segoe UI} -size 9")
336         self.label_ftpPassword.configure(foreground="#000000")
337         self.label_ftpPassword.configure(highlightbackground="#d9d9d9")
338         self.label_ftpPassword.configure(highlightcolor="#000000")
339         self.label_ftpPassword.configure(text='''FTP Passwort:''')
340 
341         self.entry_ftpPassword = tk.Entry(self.frame_FTP)
342         self.entry_ftpPassword.place(relx=0.344, rely=0.779, height=20
343                 , relwidth=0.624, bordermode='ignore')
344         self.entry_ftpPassword.configure(background="white")
345         self.entry_ftpPassword.configure(disabledforeground="#a3a3a3")
346         self.entry_ftpPassword.configure(font="-family {Courier New} -size 10")
347         self.entry_ftpPassword.configure(foreground="#000000")
348         self.entry_ftpPassword.configure(highlightbackground="#d9d9d9")
349         self.entry_ftpPassword.configure(highlightcolor="#000000")
350         self.entry_ftpPassword.configure(insertbackground="#000000")
351         self.entry_ftpPassword.configure(selectbackground="#d9d9d9")
352         self.entry_ftpPassword.configure(selectforeground="black")
353         self.entry_ftpPassword_tooltip = \
354         ToolTip(self.entry_ftpPassword, '''FTP Host ohne Port eintragen''')
355 
356         self.frame_Updater = tk.LabelFrame(self.tabs_t2)
357         self.frame_Updater.place(relx=0.017, rely=0.049, relheight=0.705
358                 , relwidth=0.475)
359         self.frame_Updater.configure(relief='groove')
360         self.frame_Updater.configure(font="-family {Segoe UI} -size 9")
361         self.frame_Updater.configure(foreground="#000000")
362         self.frame_Updater.configure(text='''Einstellungen''')
363         self.frame_Updater.configure(background="#d9d9d9")
364         self.frame_Updater.configure(highlightbackground="#d9d9d9")
365         self.frame_Updater.configure(highlightcolor="#000000")
366 
367         self.label_updaterIntervall = tk.Label(self.frame_Updater)
368         self.label_updaterIntervall.place(relx=0.036, rely=0.14, height=19
369                 , width=144, bordermode='ignore')
370         self.label_updaterIntervall.configure(activebackground="#d9d9d9")
371         self.label_updaterIntervall.configure(activeforeground="black")
372         self.label_updaterIntervall.configure(anchor='w')
373         self.label_updaterIntervall.configure(background="#d9d9d9")
374         self.label_updaterIntervall.configure(compound='left')
375         self.label_updaterIntervall.configure(disabledforeground="#a3a3a3")
376         self.label_updaterIntervall.configure(font="-family {Segoe UI} -size 9")
377         self.label_updaterIntervall.configure(foreground="#000000")
378         self.label_updaterIntervall.configure(highlightbackground="#d9d9d9")
379         self.label_updaterIntervall.configure(highlightcolor="#000000")
380         self.label_updaterIntervall.configure(text='''Intervall''')
381 
382         self.combobox_updaterIntervall = ttk.Combobox(self.frame_Updater)
383         self.combobox_updaterIntervall.place(relx=0.643, rely=0.155
384                 , relheight=0.132, relwidth=0.311, bordermode='ignore')
385         self.combobox_updaterIntervall.configure(font="-family {Segoe UI} -size 9")
386         self.combobox_updaterIntervall.configure(textvariable=self.combobox)
387 
388         self.label_updaterTimes = tk.Label(self.frame_Updater)
389         self.label_updaterTimes.place(relx=0.036, rely=0.388, height=19
390                 , width=144, bordermode='ignore')
391         self.label_updaterTimes.configure(activebackground="#d9d9d9")
392         self.label_updaterTimes.configure(activeforeground="black")
393         self.label_updaterTimes.configure(anchor='w')
394         self.label_updaterTimes.configure(background="#d9d9d9")
395         self.label_updaterTimes.configure(compound='left')
396         self.label_updaterTimes.configure(disabledforeground="#a3a3a3")
397         self.label_updaterTimes.configure(font="-family {Segoe UI} -size 9")
398         self.label_updaterTimes.configure(foreground="#000000")
399         self.label_updaterTimes.configure(highlightbackground="#d9d9d9")
400         self.label_updaterTimes.configure(highlightcolor="#000000")
401         self.label_updaterTimes.configure(text='''Ausführung''')
402 
403         self.entry_updaterTimes = tk.Entry(self.frame_Updater)
404         self.entry_updaterTimes.place(relx=0.643, rely=0.349, height=20
405                 , relwidth=0.3, bordermode='ignore')
406         self.entry_updaterTimes.configure(background="white")
407         self.entry_updaterTimes.configure(disabledforeground="#a3a3a3")
408         self.entry_updaterTimes.configure(font="-family {Courier New} -size 10")
409         self.entry_updaterTimes.configure(foreground="#000000")
410         self.entry_updaterTimes.configure(highlightbackground="#d9d9d9")
411         self.entry_updaterTimes.configure(highlightcolor="#000000")
412         self.entry_updaterTimes.configure(insertbackground="#000000")
413         self.entry_updaterTimes.configure(selectbackground="#d9d9d9")
414         self.entry_updaterTimes.configure(selectforeground="black")
415 
416         self.info_updaterText = tk.Message(self.frame_Updater)
417         self.info_updaterText.place(relx=0.107, rely=0.55, relheight=0.341
418                 , relwidth=0.75, bordermode='ignore')
419         self.info_updaterText.configure(background="#d9d9d9")
420         self.info_updaterText.configure(font="-family {Segoe UI} -size 9")
421         self.info_updaterText.configure(foreground="#000000")
422         self.info_updaterText.configure(highlightbackground="#d9d9d9")
423         self.info_updaterText.configure(highlightcolor="#000000")
424         self.info_updaterText.configure(justify='center')
425         self.info_updaterText.configure(padx="1")
426         self.info_updaterText.configure(pady="1")
427         self.info_updaterText.configure(relief="ridge")
428         self.info_updaterText.configure(text='''Hier bitte die Uhrzeit einstellen, wann das Script ausgeführt werden soll. Mit Komma getrennt.''')
429         self.info_updaterText.configure(width=210)
430 
431         self.btn_updaterStart = tk.Button(self.tabs_t2)
432         self.btn_updaterStart.place(relx=0.017, rely=0.825, height=26, width=47)
433         self.btn_updaterStart.configure(activebackground="#d9d9d9")
434         self.btn_updaterStart.configure(activeforeground="black")
435         self.btn_updaterStart.configure(background="#d9d9d9")
436         self.btn_updaterStart.configure(disabledforeground="#a3a3a3")
437         self.btn_updaterStart.configure(font="-family {Segoe UI} -size 9")
438         self.btn_updaterStart.configure(foreground="#000000")
439         self.btn_updaterStart.configure(highlightbackground="#d9d9d9")
440         self.btn_updaterStart.configure(highlightcolor="#000000")
441         self.btn_updaterStart.configure(text='''Start''')
442 
443         self.btn_updaterStop = tk.Button(self.tabs_t2)
444         self.btn_updaterStop.place(relx=0.119, rely=0.825, height=26, width=47)
445         self.btn_updaterStop.configure(activebackground="#d9d9d9")
446         self.btn_updaterStop.configure(activeforeground="black")
447         self.btn_updaterStop.configure(background="#d9d9d9")
448         self.btn_updaterStop.configure(disabledforeground="#a3a3a3")
449         self.btn_updaterStop.configure(font="-family {Segoe UI} -size 9")
450         self.btn_updaterStop.configure(foreground="#000000")
451         self.btn_updaterStop.configure(highlightbackground="#d9d9d9")
452         self.btn_updaterStop.configure(highlightcolor="#000000")
453         self.btn_updaterStop.configure(text='''Stop''')
454 
455         self.btn_updaterSave = tk.Button(self.tabs_t2)
456         self.btn_updaterSave.place(relx=0.374, rely=0.825, height=26, width=67)
457         self.btn_updaterSave.configure(activebackground="#d9d9d9")
458         self.btn_updaterSave.configure(activeforeground="black")
459         self.btn_updaterSave.configure(background="#d9d9d9")
460         self.btn_updaterSave.configure(disabledforeground="#a3a3a3")
461         self.btn_updaterSave.configure(font="-family {Segoe UI} -size 9")
462         self.btn_updaterSave.configure(foreground="#000000")
463         self.btn_updaterSave.configure(highlightbackground="#d9d9d9")
464         self.btn_updaterSave.configure(highlightcolor="#000000")
465         self.btn_updaterSave.configure(text='''Speichern''')
466 
467         self.frame_updaterSchedules = tk.LabelFrame(self.tabs_t2)
468         self.frame_updaterSchedules.place(relx=0.509, rely=0.055, relheight=0.896
469                 , relwidth=0.475)
470         self.frame_updaterSchedules.configure(relief='groove')
471         self.frame_updaterSchedules.configure(font="-family {Segoe UI} -size 9")
472         self.frame_updaterSchedules.configure(foreground="#000000")
473         self.frame_updaterSchedules.configure(text='''Geplante Aufgaben''')
474         self.frame_updaterSchedules.configure(background="#d9d9d9")
475         self.frame_updaterSchedules.configure(highlightbackground="#d9d9d9")
476         self.frame_updaterSchedules.configure(highlightcolor="#000000")
477 
478         self.canvas_updaterSchedules = tk.Canvas(self.frame_updaterSchedules)
479         self.canvas_updaterSchedules.place(relx=0.036, rely=0.11, relheight=0.823
480                 , relwidth=0.904, bordermode='ignore')
481         self.canvas_updaterSchedules.configure(background="#d9d9d9")
482         self.canvas_updaterSchedules.configure(borderwidth="2")
483         self.canvas_updaterSchedules.configure(highlightbackground="#d9d9d9")
484         self.canvas_updaterSchedules.configure(highlightcolor="#000000")
485         self.canvas_updaterSchedules.configure(insertbackground="#000000")
486         self.canvas_updaterSchedules.configure(relief="ridge")
487         self.canvas_updaterSchedules.configure(selectbackground="#d9d9d9")
488         self.canvas_updaterSchedules.configure(selectforeground="black")
489 
490         self.frame_Backuper = tk.LabelFrame(self.tabs_t3)
491         self.frame_Backuper.place(relx=0.017, rely=0.049, relheight=0.705
492                 , relwidth=0.475)
493         self.frame_Backuper.configure(relief='groove')
494         self.frame_Backuper.configure(font="-family {Segoe UI} -size 9")
495         self.frame_Backuper.configure(foreground="#000000")
496         self.frame_Backuper.configure(text='''Einstellungen''')
497         self.frame_Backuper.configure(background="#d9d9d9")
498         self.frame_Backuper.configure(highlightbackground="#d9d9d9")
499         self.frame_Backuper.configure(highlightcolor="#000000")
500 
501         self.Entry7 = tk.Entry(self.frame_Backuper)
502         self.Entry7.place(relx=0.643, rely=0.14, height=20, relwidth=0.3
503                 , bordermode='ignore')
504         self.Entry7.configure(background="white")
505         self.Entry7.configure(disabledforeground="#a3a3a3")
506         self.Entry7.configure(font="-family {Courier New} -size 10")
507         self.Entry7.configure(foreground="#000000")
508         self.Entry7.configure(highlightbackground="#d9d9d9")
509         self.Entry7.configure(highlightcolor="#000000")
510         self.Entry7.configure(insertbackground="#000000")
511         self.Entry7.configure(selectbackground="#d9d9d9")
512         self.Entry7.configure(selectforeground="black")
513 
514         self.Checkbutton1 = tk.Checkbutton(self.frame_Backuper)
515         self.Checkbutton1.place(relx=0.643, rely=0.349, relheight=0.171
516                 , relwidth=0.075, bordermode='ignore')
517         self.Checkbutton1.configure(activebackground="#d9d9d9")
518         self.Checkbutton1.configure(activeforeground="black")
519         self.Checkbutton1.configure(anchor='w')
520         self.Checkbutton1.configure(background="#d9d9d9")
521         self.Checkbutton1.configure(compound='left')
522         self.Checkbutton1.configure(disabledforeground="#a3a3a3")
523         self.Checkbutton1.configure(font="-family {Segoe UI} -size 9")
524         self.Checkbutton1.configure(foreground="#000000")
525         self.Checkbutton1.configure(highlightbackground="#d9d9d9")
526         self.Checkbutton1.configure(highlightcolor="#000000")
527         self.Checkbutton1.configure(justify='left')
528         self.Checkbutton1.configure(variable=self.che64)
529 
530         self.Checkbutton2 = tk.Checkbutton(self.frame_Backuper)
531         self.Checkbutton2.place(relx=0.643, rely=0.55, relheight=0.171
532                 , relwidth=0.075, bordermode='ignore')
533         self.Checkbutton2.configure(activebackground="#d9d9d9")
534         self.Checkbutton2.configure(activeforeground="black")
535         self.Checkbutton2.configure(anchor='w')
536         self.Checkbutton2.configure(background="#d9d9d9")
537         self.Checkbutton2.configure(compound='left')
538         self.Checkbutton2.configure(disabledforeground="#a3a3a3")
539         self.Checkbutton2.configure(font="-family {Segoe UI} -size 9")
540         self.Checkbutton2.configure(foreground="#000000")
541         self.Checkbutton2.configure(highlightbackground="#d9d9d9")
542         self.Checkbutton2.configure(highlightcolor="#000000")
543         self.Checkbutton2.configure(justify='left')
544         self.Checkbutton2.configure(variable=self.che68)
545 
546         self.Entry8 = tk.Entry(self.frame_Backuper)
547         self.Entry8.place(relx=0.643, rely=0.76, height=20, relwidth=0.3
548                 , bordermode='ignore')
549         self.Entry8.configure(background="white")
550         self.Entry8.configure(disabledforeground="#a3a3a3")
551         self.Entry8.configure(font="-family {Courier New} -size 10")
552         self.Entry8.configure(foreground="#000000")
553         self.Entry8.configure(highlightbackground="#d9d9d9")
554         self.Entry8.configure(highlightcolor="#000000")
555         self.Entry8.configure(insertbackground="#000000")
556         self.Entry8.configure(selectbackground="#d9d9d9")
557         self.Entry8.configure(selectforeground="black")
558 
559         self.label_backuperIntervall = tk.Label(self.frame_Backuper)
560         self.label_backuperIntervall.place(relx=0.036, rely=0.14, height=19
561                 , width=144, bordermode='ignore')
562         self.label_backuperIntervall.configure(activebackground="#d9d9d9")
563         self.label_backuperIntervall.configure(activeforeground="black")
564         self.label_backuperIntervall.configure(anchor='w')
565         self.label_backuperIntervall.configure(background="#d9d9d9")
566         self.label_backuperIntervall.configure(compound='left')
567         self.label_backuperIntervall.configure(disabledforeground="#a3a3a3")
568         self.label_backuperIntervall.configure(font="-family {Segoe UI} -size 9")
569         self.label_backuperIntervall.configure(foreground="#000000")
570         self.label_backuperIntervall.configure(highlightbackground="#d9d9d9")
571         self.label_backuperIntervall.configure(highlightcolor="#000000")
572         self.label_backuperIntervall.configure(text='''Intervall in Minuten:''')
573 
574         self.check_backuperRotation = tk.Label(self.frame_Backuper)
575         self.check_backuperRotation.place(relx=0.036, rely=0.349, height=18
576                 , width=144, bordermode='ignore')
577         self.check_backuperRotation.configure(activebackground="#d9d9d9")
578         self.check_backuperRotation.configure(activeforeground="black")
579         self.check_backuperRotation.configure(anchor='w')
580         self.check_backuperRotation.configure(background="#d9d9d9")
581         self.check_backuperRotation.configure(compound='left')
582         self.check_backuperRotation.configure(disabledforeground="#a3a3a3")
583         self.check_backuperRotation.configure(font="-family {Segoe UI} -size 9")
584         self.check_backuperRotation.configure(foreground="#000000")
585         self.check_backuperRotation.configure(highlightbackground="#d9d9d9")
586         self.check_backuperRotation.configure(highlightcolor="#000000")
587         self.check_backuperRotation.configure(text='''Rotation aktivieren?''')
588 
589         self.check_backuperZip = tk.Label(self.frame_Backuper)
590         self.check_backuperZip.place(relx=0.036, rely=0.55, height=19, width=144
591                 , bordermode='ignore')
592         self.check_backuperZip.configure(activebackground="#d9d9d9")
593         self.check_backuperZip.configure(activeforeground="black")
594         self.check_backuperZip.configure(anchor='w')
595         self.check_backuperZip.configure(background="#d9d9d9")
596         self.check_backuperZip.configure(compound='left')
597         self.check_backuperZip.configure(disabledforeground="#a3a3a3")
598         self.check_backuperZip.configure(font="-family {Segoe UI} -size 9")
599         self.check_backuperZip.configure(foreground="#000000")
600         self.check_backuperZip.configure(highlightbackground="#d9d9d9")
601         self.check_backuperZip.configure(highlightcolor="#000000")
602         self.check_backuperZip.configure(text='''Zippen aktivieren?''')
603 
604         self.entry_backuperAmount = tk.Label(self.frame_Backuper)
605         self.entry_backuperAmount.place(relx=0.036, rely=0.76, height=19
606                 , width=144, bordermode='ignore')
607         self.entry_backuperAmount.configure(activebackground="#d9d9d9")
608         self.entry_backuperAmount.configure(activeforeground="black")
609         self.entry_backuperAmount.configure(anchor='w')
610         self.entry_backuperAmount.configure(background="#d9d9d9")
611         self.entry_backuperAmount.configure(compound='left')
612         self.entry_backuperAmount.configure(disabledforeground="#a3a3a3")
613         self.entry_backuperAmount.configure(font="-family {Segoe UI} -size 9")
614         self.entry_backuperAmount.configure(foreground="#000000")
615         self.entry_backuperAmount.configure(highlightbackground="#d9d9d9")
616         self.entry_backuperAmount.configure(highlightcolor="#000000")
617         self.entry_backuperAmount.configure(text='''Anzahl an Backups:''')
618 
619         self.btn_backuperStart = tk.Button(self.tabs_t3)
620         self.btn_backuperStart.place(relx=0.017, rely=0.825, height=26, width=47)
621 
622         self.btn_backuperStart.configure(activebackground="#d9d9d9")
623         self.btn_backuperStart.configure(activeforeground="black")
624         self.btn_backuperStart.configure(background="#d9d9d9")
625         self.btn_backuperStart.configure(disabledforeground="#a3a3a3")
626         self.btn_backuperStart.configure(font="-family {Segoe UI} -size 9")
627         self.btn_backuperStart.configure(foreground="#000000")
628         self.btn_backuperStart.configure(highlightbackground="#d9d9d9")
629         self.btn_backuperStart.configure(highlightcolor="#000000")
630         self.btn_backuperStart.configure(text='''Start''')
631 
632         self.btn_backuperStop = tk.Button(self.tabs_t3)
633         self.btn_backuperStop.place(relx=0.119, rely=0.825, height=26, width=47)
634         self.btn_backuperStop.configure(activebackground="#d9d9d9")
635         self.btn_backuperStop.configure(activeforeground="black")
636         self.btn_backuperStop.configure(background="#d9d9d9")
637         self.btn_backuperStop.configure(disabledforeground="#a3a3a3")
638         self.btn_backuperStop.configure(font="-family {Segoe UI} -size 9")
639         self.btn_backuperStop.configure(foreground="#000000")
640         self.btn_backuperStop.configure(highlightbackground="#d9d9d9")
641         self.btn_backuperStop.configure(highlightcolor="#000000")
642         self.btn_backuperStop.configure(text='''Stop''')
643 
644         self.btn_backuperSave = tk.Button(self.tabs_t3)
645         self.btn_backuperSave.place(relx=0.374, rely=0.825, height=26, width=67)
646         self.btn_backuperSave.configure(activebackground="#d9d9d9")
647         self.btn_backuperSave.configure(activeforeground="black")
648         self.btn_backuperSave.configure(background="#d9d9d9")
649         self.btn_backuperSave.configure(disabledforeground="#a3a3a3")
650         self.btn_backuperSave.configure(font="-family {Segoe UI} -size 9")
651         self.btn_backuperSave.configure(foreground="#000000")
652         self.btn_backuperSave.configure(highlightbackground="#d9d9d9")
653         self.btn_backuperSave.configure(highlightcolor="#000000")
654         self.btn_backuperSave.configure(text='''Speichern''')
655 
656         self.frame_BackuperFiles = tk.LabelFrame(self.tabs_t3)
657         self.frame_BackuperFiles.place(relx=0.509, rely=0.055, relheight=0.896
658                 , relwidth=0.475)
659         self.frame_BackuperFiles.configure(relief='groove')
660         self.frame_BackuperFiles.configure(font="-family {Segoe UI} -size 9")
661         self.frame_BackuperFiles.configure(foreground="#000000")
662         self.frame_BackuperFiles.configure(text='''Vorhandene Backups''')
663         self.frame_BackuperFiles.configure(background="#d9d9d9")
664         self.frame_BackuperFiles.configure(highlightbackground="#d9d9d9")
665         self.frame_BackuperFiles.configure(highlightcolor="#000000")
666 
667         self.canvas_backuperFiles = tk.Canvas(self.frame_BackuperFiles)
668         self.canvas_backuperFiles.place(relx=0.036, rely=0.11, relheight=0.823
669                 , relwidth=0.939, bordermode='ignore')
670         self.canvas_backuperFiles.configure(background="#d9d9d9")
671         self.canvas_backuperFiles.configure(borderwidth="2")
672         self.canvas_backuperFiles.configure(highlightbackground="#d9d9d9")
673         self.canvas_backuperFiles.configure(highlightcolor="#000000")
674         self.canvas_backuperFiles.configure(insertbackground="#000000")
675         self.canvas_backuperFiles.configure(relief="ridge")
676         self.canvas_backuperFiles.configure(selectbackground="#d9d9d9")
677         self.canvas_backuperFiles.configure(selectforeground="black")
678 
679         self.frame_Options = tk.LabelFrame(self.tabs_t4)
680         self.frame_Options.place(relx=0.017, rely=0.049, relheight=0.705
681                 , relwidth=0.475)
682         self.frame_Options.configure(relief='groove')
683         self.frame_Options.configure(font="-family {Segoe UI} -size 9")
684         self.frame_Options.configure(foreground="#000000")
685         self.frame_Options.configure(text='''Einstellungen''')
686         self.frame_Options.configure(background="#d9d9d9")
687         self.frame_Options.configure(highlightbackground="#d9d9d9")
688         self.frame_Options.configure(highlightcolor="#000000")
689 
690         self.label_optionsSendMails = tk.Label(self.frame_Options)
691         self.label_optionsSendMails.place(relx=0.036, rely=0.233, height=20
692                 , width=154, bordermode='ignore')
693         self.label_optionsSendMails.configure(activebackground="#d9d9d9")
694         self.label_optionsSendMails.configure(activeforeground="black")
695         self.label_optionsSendMails.configure(anchor='w')
696         self.label_optionsSendMails.configure(background="#d9d9d9")
697         self.label_optionsSendMails.configure(compound='left')
698         self.label_optionsSendMails.configure(disabledforeground="#a3a3a3")
699         self.label_optionsSendMails.configure(font="-family {Segoe UI} -size 9")
700         self.label_optionsSendMails.configure(foreground="#000000")
701         self.label_optionsSendMails.configure(highlightbackground="#d9d9d9")
702         self.label_optionsSendMails.configure(highlightcolor="#000000")
703         self.label_optionsSendMails.configure(text='''Benachrichtigungen:''')
704 
705         self.check_optionsSendMail = tk.Checkbutton(self.frame_Options)
706         self.check_optionsSendMail.place(relx=0.643, rely=0.209, relheight=0.171
707                 , relwidth=0.075, bordermode='ignore')
708         self.check_optionsSendMail.configure(activebackground="#d9d9d9")
709         self.check_optionsSendMail.configure(activeforeground="black")
710         self.check_optionsSendMail.configure(anchor='w')
711         self.check_optionsSendMail.configure(background="#d9d9d9")
712         self.check_optionsSendMail.configure(compound='left')
713         self.check_optionsSendMail.configure(disabledforeground="#a3a3a3")
714         self.check_optionsSendMail.configure(font="-family {Segoe UI} -size 9")
715         self.check_optionsSendMail.configure(foreground="#000000")
716         self.check_optionsSendMail.configure(highlightbackground="#d9d9d9")
717         self.check_optionsSendMail.configure(highlightcolor="#000000")
718         self.check_optionsSendMail.configure(justify='left')
719         self.check_optionsSendMail.configure(variable=self.che79)
720 
721         self.label_optionsUseSMTP = tk.Label(self.frame_Options)
722         self.label_optionsUseSMTP.place(relx=0.036, rely=0.481, height=20
723                 , width=144, bordermode='ignore')
724         self.label_optionsUseSMTP.configure(activebackground="#d9d9d9")
725         self.label_optionsUseSMTP.configure(activeforeground="black")
726         self.label_optionsUseSMTP.configure(anchor='w')
727         self.label_optionsUseSMTP.configure(background="#d9d9d9")
728         self.label_optionsUseSMTP.configure(compound='left')
729         self.label_optionsUseSMTP.configure(disabledforeground="#a3a3a3")
730         self.label_optionsUseSMTP.configure(font="-family {Segoe UI} -size 9")
731         self.label_optionsUseSMTP.configure(foreground="#000000")
732         self.label_optionsUseSMTP.configure(highlightbackground="#d9d9d9")
733         self.label_optionsUseSMTP.configure(highlightcolor="#000000")
734         self.label_optionsUseSMTP.configure(text='''Mailserver SMTP:''')
735 
736         self.check_optionsUseSMTP = tk.Checkbutton(self.frame_Options)
737         self.check_optionsUseSMTP.place(relx=0.643, rely=0.481, relheight=0.171
738                 , relwidth=0.075, bordermode='ignore')
739         self.check_optionsUseSMTP.configure(activebackground="#d9d9d9")
740         self.check_optionsUseSMTP.configure(activeforeground="black")
741         self.check_optionsUseSMTP.configure(anchor='w')
742         self.check_optionsUseSMTP.configure(background="#d9d9d9")
743         self.check_optionsUseSMTP.configure(compound='left')
744         self.check_optionsUseSMTP.configure(disabledforeground="#a3a3a3")
745         self.check_optionsUseSMTP.configure(font="-family {Segoe UI} -size 9")
746         self.check_optionsUseSMTP.configure(foreground="#000000")
747         self.check_optionsUseSMTP.configure(highlightbackground="#d9d9d9")
748         self.check_optionsUseSMTP.configure(highlightcolor="#000000")
749         self.check_optionsUseSMTP.configure(justify='left')
750         self.check_optionsUseSMTP.configure(variable=self.che81)
751 
752         self.label_optionsDebugLevel = tk.Label(self.frame_Options)
753         self.label_optionsDebugLevel.place(relx=0.036, rely=0.775, height=19
754                 , width=144, bordermode='ignore')
755         self.label_optionsDebugLevel.configure(activebackground="#d9d9d9")
756         self.label_optionsDebugLevel.configure(activeforeground="black")
757         self.label_optionsDebugLevel.configure(anchor='w')
758         self.label_optionsDebugLevel.configure(background="#d9d9d9")
759         self.label_optionsDebugLevel.configure(compound='left')
760         self.label_optionsDebugLevel.configure(disabledforeground="#a3a3a3")
761         self.label_optionsDebugLevel.configure(font="-family {Segoe UI} -size 9")
762         self.label_optionsDebugLevel.configure(foreground="#000000")
763         self.label_optionsDebugLevel.configure(highlightbackground="#d9d9d9")
764         self.label_optionsDebugLevel.configure(highlightcolor="#000000")
765         self.label_optionsDebugLevel.configure(text='''Debug-Level''')
766 
767         self.combobox_optionsDdebugLevel = ttk.Combobox(self.frame_Options)
768         self.combobox_optionsDdebugLevel.place(relx=0.643, rely=0.76
769                 , relheight=0.132, relwidth=0.311, bordermode='ignore')
770         self.combobox_optionsDdebugLevel.configure(font="-family {Segoe UI} -size 9")
771         self.combobox_optionsDdebugLevel.configure(textvariable=self.combobox)
772 
773         self.canvas_StatusSMTP = tk.Canvas(self.tabs_t4)
774         self.canvas_StatusSMTP.place(relx=0.017, rely=0.776, relheight=0.158
775                 , relwidth=0.328)
776         self.canvas_StatusSMTP.configure(background="#d9d9d9")
777         self.canvas_StatusSMTP.configure(borderwidth="2")
778         self.canvas_StatusSMTP.configure(highlightbackground="#d9d9d9")
779         self.canvas_StatusSMTP.configure(highlightcolor="#000000")
780         self.canvas_StatusSMTP.configure(insertbackground="#000000")
781         self.canvas_StatusSMTP.configure(relief="ridge")
782         self.canvas_StatusSMTP.configure(selectbackground="#d9d9d9")
783         self.canvas_StatusSMTP.configure(selectforeground="black")
784 
785         self.btn_TestSMTP = tk.Button(self.tabs_t4)
786         self.btn_TestSMTP.place(relx=0.39, rely=0.776, height=26, width=57)
787         self.btn_TestSMTP.configure(activebackground="#d9d9d9")
788         self.btn_TestSMTP.configure(activeforeground="black")
789         self.btn_TestSMTP.configure(background="#d9d9d9")
790         self.btn_TestSMTP.configure(disabledforeground="#a3a3a3")
791         self.btn_TestSMTP.configure(font="-family {Segoe UI} -size 9")
792         self.btn_TestSMTP.configure(foreground="#000000")
793         self.btn_TestSMTP.configure(highlightbackground="#d9d9d9")
794         self.btn_TestSMTP.configure(highlightcolor="#000000")
795         self.btn_TestSMTP.configure(text='''Testen''')
796 
797         self.frame_SMTP = tk.LabelFrame(self.tabs_t4)
798         self.frame_SMTP.place(relx=0.509, rely=0.049, relheight=0.896
799                 , relwidth=0.475)
800         self.frame_SMTP.configure(relief='groove')
801         self.frame_SMTP.configure(font="-family {Segoe UI} -size 9")
802         self.frame_SMTP.configure(foreground="#000000")
803         self.frame_SMTP.configure(text='''SMTP''')
804         self.frame_SMTP.configure(background="#d9d9d9")
805         self.frame_SMTP.configure(highlightbackground="#d9d9d9")
806         self.frame_SMTP.configure(highlightcolor="#000000")
807 
808         self.label_ServerSMTP = tk.Label(self.frame_SMTP)
809         self.label_ServerSMTP.place(relx=0.036, rely=0.165, height=18, width=34
810                 , bordermode='ignore')
811         self.label_ServerSMTP.configure(activebackground="#d9d9d9")
812         self.label_ServerSMTP.configure(activeforeground="black")
813         self.label_ServerSMTP.configure(anchor='w')
814         self.label_ServerSMTP.configure(background="#d9d9d9")
815         self.label_ServerSMTP.configure(compound='left')
816         self.label_ServerSMTP.configure(disabledforeground="#a3a3a3")
817         self.label_ServerSMTP.configure(font="-family {Segoe UI} -size 9")
818         self.label_ServerSMTP.configure(foreground="#000000")
819         self.label_ServerSMTP.configure(highlightbackground="#d9d9d9")
820         self.label_ServerSMTP.configure(highlightcolor="#000000")
821         self.label_ServerSMTP.configure(text='''Server:''')
822 
823         self.entry_serverSMTP = tk.Entry(self.frame_SMTP)
824         self.entry_serverSMTP.place(relx=0.429, rely=0.165, height=20
825                 , relwidth=0.514, bordermode='ignore')
826         self.entry_serverSMTP.configure(background="white")
827         self.entry_serverSMTP.configure(disabledforeground="#a3a3a3")
828         self.entry_serverSMTP.configure(font="-family {Courier New} -size 10")
829         self.entry_serverSMTP.configure(foreground="#000000")
830         self.entry_serverSMTP.configure(highlightbackground="#d9d9d9")
831         self.entry_serverSMTP.configure(highlightcolor="#000000")
832         self.entry_serverSMTP.configure(insertbackground="#000000")
833         self.entry_serverSMTP.configure(selectbackground="#d9d9d9")
834         self.entry_serverSMTP.configure(selectforeground="black")
835 
836         self.label_PortSMTP = tk.Label(self.frame_SMTP)
837         self.label_PortSMTP.place(relx=0.036, rely=0.323, height=19, width=34
838                 , bordermode='ignore')
839         self.label_PortSMTP.configure(activebackground="#d9d9d9")
840         self.label_PortSMTP.configure(activeforeground="black")
841         self.label_PortSMTP.configure(anchor='w')
842         self.label_PortSMTP.configure(background="#d9d9d9")
843         self.label_PortSMTP.configure(compound='left')
844         self.label_PortSMTP.configure(disabledforeground="#a3a3a3")
845         self.label_PortSMTP.configure(font="-family {Segoe UI} -size 9")
846         self.label_PortSMTP.configure(foreground="#000000")
847         self.label_PortSMTP.configure(highlightbackground="#d9d9d9")
848         self.label_PortSMTP.configure(highlightcolor="#000000")
849         self.label_PortSMTP.configure(text='''Port:''')
850 
851         self.entry_PortSMTP = tk.Entry(self.frame_SMTP)
852         self.entry_PortSMTP.place(relx=0.429, rely=0.323, height=20, relwidth=0.3
853                 , bordermode='ignore')
854         self.entry_PortSMTP.configure(background="white")
855         self.entry_PortSMTP.configure(disabledforeground="#a3a3a3")
856         self.entry_PortSMTP.configure(font="-family {Courier New} -size 10")
857         self.entry_PortSMTP.configure(foreground="#000000")
858         self.entry_PortSMTP.configure(highlightbackground="#d9d9d9")
859         self.entry_PortSMTP.configure(highlightcolor="#000000")
860         self.entry_PortSMTP.configure(insertbackground="#000000")
861         self.entry_PortSMTP.configure(selectbackground="#d9d9d9")
862         self.entry_PortSMTP.configure(selectforeground="black")
863 
864         self.label_UserSMTP = tk.Label(self.frame_SMTP)
865         self.label_UserSMTP.place(relx=0.036, rely=0.488, height=19, width=94
866                 , bordermode='ignore')
867         self.label_UserSMTP.configure(activebackground="#d9d9d9")
868         self.label_UserSMTP.configure(activeforeground="black")
869         self.label_UserSMTP.configure(anchor='w')
870         self.label_UserSMTP.configure(background="#d9d9d9")
871         self.label_UserSMTP.configure(compound='left')
872         self.label_UserSMTP.configure(disabledforeground="#a3a3a3")
873         self.label_UserSMTP.configure(font="-family {Segoe UI} -size 9")
874         self.label_UserSMTP.configure(foreground="#000000")
875         self.label_UserSMTP.configure(highlightbackground="#d9d9d9")
876         self.label_UserSMTP.configure(highlightcolor="#000000")
877         self.label_UserSMTP.configure(text='''Benutzername:''')
878 
879         self.entry_UserSMTP = tk.Entry(self.frame_SMTP)
880         self.entry_UserSMTP.place(relx=0.429, rely=0.488, height=20
881                 , relwidth=0.514, bordermode='ignore')
882         self.entry_UserSMTP.configure(background="white")
883         self.entry_UserSMTP.configure(disabledforeground="#a3a3a3")
884         self.entry_UserSMTP.configure(font="-family {Courier New} -size 10")
885         self.entry_UserSMTP.configure(foreground="#000000")
886         self.entry_UserSMTP.configure(highlightbackground="#d9d9d9")
887         self.entry_UserSMTP.configure(highlightcolor="#000000")
888         self.entry_UserSMTP.configure(insertbackground="#000000")
889         self.entry_UserSMTP.configure(selectbackground="#d9d9d9")
890         self.entry_UserSMTP.configure(selectforeground="black")
891 
892         self.label_PasswordSMTP = tk.Label(self.frame_SMTP)
893         self.label_PasswordSMTP.place(relx=0.036, rely=0.646, height=19, width=94
894                 , bordermode='ignore')
895         self.label_PasswordSMTP.configure(activebackground="#d9d9d9")
896         self.label_PasswordSMTP.configure(activeforeground="black")
897         self.label_PasswordSMTP.configure(anchor='w')
898         self.label_PasswordSMTP.configure(background="#d9d9d9")
899         self.label_PasswordSMTP.configure(compound='left')
900         self.label_PasswordSMTP.configure(disabledforeground="#a3a3a3")
901         self.label_PasswordSMTP.configure(font="-family {Segoe UI} -size 9")
902         self.label_PasswordSMTP.configure(foreground="#000000")
903         self.label_PasswordSMTP.configure(highlightbackground="#d9d9d9")
904         self.label_PasswordSMTP.configure(highlightcolor="#000000")
905         self.label_PasswordSMTP.configure(text='''Passwort:''')
906 
907         self.entry_PasswordSMTP = tk.Entry(self.frame_SMTP)
908         self.entry_PasswordSMTP.place(relx=0.429, rely=0.646, height=20
909                 , relwidth=0.514, bordermode='ignore')
910         self.entry_PasswordSMTP.configure(background="white")
911         self.entry_PasswordSMTP.configure(disabledforeground="#a3a3a3")
912         self.entry_PasswordSMTP.configure(font="-family {Courier New} -size 10")
913         self.entry_PasswordSMTP.configure(foreground="#000000")
914         self.entry_PasswordSMTP.configure(highlightbackground="#d9d9d9")
915         self.entry_PasswordSMTP.configure(highlightcolor="#000000")
916         self.entry_PasswordSMTP.configure(insertbackground="#000000")
917         self.entry_PasswordSMTP.configure(selectbackground="#d9d9d9")
918         self.entry_PasswordSMTP.configure(selectforeground="black")
919 
920         self.label_ReceiverSMTP = tk.Label(self.frame_SMTP)
921         self.label_ReceiverSMTP.place(relx=0.036, rely=0.811, height=19
922                 , width=104, bordermode='ignore')
923         self.label_ReceiverSMTP.configure(activebackground="#d9d9d9")
924         self.label_ReceiverSMTP.configure(activeforeground="black")
925         self.label_ReceiverSMTP.configure(anchor='w')
926         self.label_ReceiverSMTP.configure(background="#d9d9d9")
927         self.label_ReceiverSMTP.configure(compound='left')
928         self.label_ReceiverSMTP.configure(disabledforeground="#a3a3a3")
929         self.label_ReceiverSMTP.configure(font="-family {Segoe UI} -size 9")
930         self.label_ReceiverSMTP.configure(foreground="#000000")
931         self.label_ReceiverSMTP.configure(highlightbackground="#d9d9d9")
932         self.label_ReceiverSMTP.configure(highlightcolor="#000000")
933         self.label_ReceiverSMTP.configure(text='''Empfänger-Email:''')
934 
935         self.entry_ReceiverSMTP = tk.Entry(self.frame_SMTP)
936         self.entry_ReceiverSMTP.place(relx=0.429, rely=0.811, height=20
937                 , relwidth=0.514, bordermode='ignore')
938         self.entry_ReceiverSMTP.configure(background="white")
939         self.entry_ReceiverSMTP.configure(disabledforeground="#a3a3a3")
940         self.entry_ReceiverSMTP.configure(font="-family {Courier New} -size 10")
941         self.entry_ReceiverSMTP.configure(foreground="#000000")
942         self.entry_ReceiverSMTP.configure(highlightbackground="#d9d9d9")
943         self.entry_ReceiverSMTP.configure(highlightcolor="#000000")
944         self.entry_ReceiverSMTP.configure(insertbackground="#000000")
945         self.entry_ReceiverSMTP.configure(selectbackground="#d9d9d9")
946         self.entry_ReceiverSMTP.configure(selectforeground="black")
947 
948         self.canvas_Console = tk.Canvas(self.top)
949         self.canvas_Console.place(relx=0.017, rely=0.657, relheight=0.323
950                 , relwidth=0.973)
951         self.canvas_Console.configure(background="#d9d9d9")
952         self.canvas_Console.configure(borderwidth="2")
953         self.canvas_Console.configure(highlightbackground="#d9d9d9")
954         self.canvas_Console.configure(highlightcolor="#000000")
955         self.canvas_Console.configure(insertbackground="#000000")
956         self.canvas_Console.configure(relief="ridge")
957         self.canvas_Console.configure(selectbackground="#d9d9d9")
958         self.canvas_Console.configure(selectforeground="black")
959 
960         self.label_Console = tk.Label(self.top)
961         self.label_Console.place(relx=0.017, rely=0.611, height=17, width=54)
962         self.label_Console.configure(activebackground="#d9d9d9")
963         self.label_Console.configure(activeforeground="black")
964         self.label_Console.configure(anchor='w')
965         self.label_Console.configure(background="#d9d9d9")
966         self.label_Console.configure(compound='left')
967         self.label_Console.configure(disabledforeground="#a3a3a3")
968         self.label_Console.configure(font="-family {Segoe UI} -size 9")
969         self.label_Console.configure(foreground="#000000")
970         self.label_Console.configure(highlightbackground="#d9d9d9")
971         self.label_Console.configure(highlightcolor="#000000")
972         self.label_Console.configure(text='''Konsole''')
973 
974 from time import time, localtime, strftime
975 class ToolTip(tk.Toplevel):
976     """ Provides a ToolTip widget for Tkinter. """
977     def __init__(self, wdgt, msg=None, msgFunc=None, delay=0.5,
978                  follow=True):
979         self.wdgt = wdgt
980         self.parent = self.wdgt.master
981         tk.Toplevel.__init__(self, self.parent, bg='black', padx=1, pady=1)
982         self.withdraw()
983         self.overrideredirect(True)
984         self.msgVar = tk.StringVar()
985         if msg is None:
986             self.msgVar.set('No message provided')
987         else:
988             self.msgVar.set(msg)
989         self.msgFunc = msgFunc
990         self.delay = delay
991         self.follow = follow
992         self.visible = 0
993         self.lastMotion = 0
994         self.msg = tk.Message(self, textvariable=self.msgVar, bg=_bgcolor,
995                    fg=_fgcolor, font="TkDefaultFont",
996                    aspect=1000)
997         self.msg.grid()
998         self.wdgt.bind('<Enter>', self.spawn, '+')
999         self.wdgt.bind('<Leave>', self.hide, '+')
1000         self.wdgt.bind('<Motion>', self.move, '+')
1001     def spawn(self, event=None):
1002         self.visible = 1
1003         self.after(int(self.delay * 1000), self.show)
1004     def show(self):
1005         if self.visible == 1 and time() - self.lastMotion > self.delay:
1006             self.visible = 2
1007         if self.visible == 2:
1008             self.deiconify()
1009     def move(self, event):
1010         self.lastMotion = time()
1011         if self.follow is False:
1012             self.withdraw()
1013             self.visible = 1
1014         self.geometry('+%i+%i' % (event.x_root + 20, event.y_root - 10))
1015         try:
1016             self.msgVar.set(self.msgFunc())
1017         except:
1018             pass
1019         self.after(int(self.delay * 1000), self.show)
1020     def hide(self, event=None):
1021         self.visible = 0
1022         self.withdraw()
1023     def update(self, msg):
1024         self.msgVar.set(msg)
1025     def configure(self, **kwargs):
1026         backgroundset = False
1027         foregroundset = False
1028         # Get the current tooltip text just in case the user doesn't provide any.
1029         current_text = self.msgVar.get()
1030         # to clear the tooltip text, use the .update method
1031         if 'debug' in kwargs.keys():
1032             debug = kwargs.pop('debug', False)
1033             if debug:
1034                 for key, value in kwargs.items():
1035                     print(f'key: {key} - value: {value}')
1036         if 'background' in kwargs.keys():
1037             background = kwargs.pop('background')
1038             backgroundset = True
1039         if 'bg' in kwargs.keys():
1040             background = kwargs.pop('bg')
1041             backgroundset = True
1042         if 'foreground' in kwargs.keys():
1043             foreground = kwargs.pop('foreground')
1044             foregroundset = True
1045         if 'fg' in kwargs.keys():
1046             foreground = kwargs.pop('fg')
1047             foregroundset = True
1048 
1049         fontd = kwargs.pop('font', None)
1050         if 'text' in kwargs.keys():
1051             text = kwargs.pop('text')
1052             if (text == '') or (text == "\n"):
1053                 text = current_text
1054             else:
1055                 self.msgVar.set(text)
1056         reliefd = kwargs.pop('relief', 'flat')
1057         justifyd = kwargs.pop('justify', 'left')
1058         padxd = kwargs.pop('padx', 1)
1059         padyd = kwargs.pop('pady', 1)
1060         borderwidthd = kwargs.pop('borderwidth', 2)
1061         wid = self.msg      # The message widget which is the actual tooltip
1062         if backgroundset:
1063             wid.config(bg=background)
1064         if foregroundset:
1065             wid.config(fg=foreground)
1066         wid.config(font=fontd)
1067         wid.config(borderwidth=borderwidthd)
1068         wid.config(relief=reliefd)
1069         wid.config(justify=justifyd)
1070         wid.config(padx=padxd)
1071         wid.config(pady=padyd)
1072 #                   End of Class ToolTip
1073 
1074 def start_up():
1075     fertiger_dialog_support.main()
1076 
1077 if __name__ == '__main__':
1078     fertiger_dialog_support.main()
1079 